### ISSUE TITLE
Add a note to "Setup & Build Tools" that understanding Webpack/Babel is optional

### ISSUE THREAD

**Issue by gaearon** [dabbott/react-express#11]
We often get issues in CRA repo from people who didn't believe CRA "just works" and tried to install Webpack or Babel on top of the generated project. To prevent issues like this, I think it would be nice to add extra notes on Babel and Webpack pages that **they are not required for learning React, and you can use `create-react-app` alone if you don't want to learn them yet**.

I've seen these notices on Environment page but they're easy to miss or forget.

**Comment by dabbott** [comment]
Great idea. I'll add a notice to the top of each of those pages.

**Comment by dabbott** [comment]
Added! https://github.com/dabbott/react-express/commit/21e6b377ed5eec96a724a2be8e1b0164847755e9
