### ISSUE TITLE
HTTPS & TLS

### ISSUE THREAD

**Issue by wayneashleyberry** [dabbott/react-express#17]
Just wondering if there's any reason http://www.react.express/ isn't running over https?

**Comment by dabbott** [comment]
There isn't anything that needs to be secure so I didn't add it. Is there a reason to be running over https otherwise?

**Comment by wayneashleyberry** [comment]
Performance & search ranking :)

https://doesmysiteneedhttps.com/

**Comment by dabbott** [comment]
Done! forgot to close this.
