### ISSUE TITLE
I got an error when run this repository: You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by EasonYou** [dabbott/react-express#27]
Firstly, sorry about my poor English.

I got an error like next, running on node 8.0.0 just clone this repository and yarn

It seems like that could not parse jsx syntax.

Can you help me?

```
 ERROR in ../~/react-disqus-thread/lib/components/DisqusThread.js
    Module parse failed: D:\mis\react-express\node_modules\react-disqus-thread\lib\components\DisqusThread.js Unexpected token (100:6)
    You may need an appropriate loader to handle this file type.
    |   render() {
    |     return (
    |       <div>
    |         <div id="disqus_thread"/>
    |       </div>
     @ ../~/react-disqus-thread/lib/main.js 1:17-53
     @ ./components/Disqus.js
     @ ./components/index.js
     @ ./pages/Animated.js
     @ ./pages lazy ^\.\/.*$
     @ ./index.js
     @ multi ./index.js
```

**Comment by dabbott** [comment]
Not sure... might have something to do with versioning? You could try with `yarn`? I've been having lots of issues with npm 8.

It's probably due to this not getting picked up: https://github.com/dabbott/react-express/blob/master/webpack.config.js#L31

**Comment by Philosec** [comment]
I too am getting this exact same error. I have the latest version of Node and NPM installed, and when I clone this repo and run install or build I get this error. I also tried yarn, as suggested, and received same error.
