### ISSUE TITLE
feture request: add a search box

### ISSUE THREAD

**Issue by zhirzh** [dabbott/react-express#28]
the look and feel of [react-express](http://www.react.express) is very similar to something created using [GitBook](https://www.gitbook.com/). Given the huge size, it is absolutely critical to have a search box there (like [redux.js.org](http://redux.js.org/))

**Comment by dabbott** [comment]
That's a great idea. 

I'm not really sure the best way to do this. Maybe Algolia? Do you have any interest in contributing?

**Comment by dabbott** [comment]
Done~
